[build]
docker_image = "ubuntu:20.04"

[target.x86_64-unknown-linux-gnu]
docker_image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:0.2.5"

[target.x86_64-apple-darwin]
docker_image = "your-docker-image-for-macos:latest"

[target.x86_64-pc-windows-gnu]
docker_image = "ghcr.io/cross-rs/x86_64-pc-windows-gnu:0.2.5"
