name: Release Binaries

on:
  release:
    types: [created]

jobs:
  release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz,tar.xz,tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: cargo fetch

      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload release binaries to GitHub
        uses: ncipollo/release-action@v1
        with:
          files: |
            target/${{ matrix.target }}/release/my_project_name-${{ matrix.target }}.${{ matrix.archive }}  # Adjust binary name
