name: Release Binaries

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz,tar.xz,tar.zst
          - target: x86_64-apple-darwin
            archive: zip    

    steps:
      - uses: actions/checkout@v4

      - name: Install necessary dependencies for cross-compilation
        run: |
          if [ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]; then
            sudo apt-get install -y mingw-w64
          elif [ "${{ matrix.target }}" == "x86_64-apple-darwin" ]; then
            sudo apt-get install -y clang
            rustup target add ${{ matrix.target }}
          fi

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload release binaries to GitHub
        uses: ncipollo/release-action@v1
        with:
          files: |
            target/${{ matrix.target }}/release/tinygrep-${{ matrix.target }}.${{ matrix.archive }}
