name: Build and Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install macOS target
        run: rustup target add x86_64-apple-darwin

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: |
          cross build --release --target x86_64-unknown-linux-gnu
          cross build --release --target x86_64-apple-darwin
          cross build --release --target x86_64-pc-windows-gnu

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: target/*/release/*
