name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: |
          cross build --release --target x86_64-unknown-linux-gnu
          cross build --release --target x86_64-apple-darwin
          cross build --release --target x86_64-pc-windows-gnu

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: target/*/release/*

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          files: target/x86_64-unknown-linux-gnu/release/my_project.tar.gz,target/x86_64-apple-darwin/release/my_project.tar.gz,target/x86_64-pc-windows-gnu/release/my_project.tar.gz
          tag: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
