name: Release Binaries

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz,tar.xz,tar.zst
          - target: x86_64-apple-darwin
            archive: zip    

    steps:
      - uses: actions/checkout@v4
      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Upload release binaries to GitHub
          uses: ncipollo/release-action@v1
          with:
            files: |
              target/${{ matrix.target }}/release/tinygrep-${{ matrix.target }}.${{ matrix.archive }}
